### ISSUE TITLE
Extract prices from dict

### ISSUE THREAD

**Issue by plguhur** [smechaab/krakenex-CurrencyViewer#1]
I have got an error with the current version:

> Price of  LTCEUR  added
> 69.00000'
> Traceback (most recent call last):
>   File "CurrencyViewer.py", line 146, in <module>
>     price[i] = float(price[i])
> ValueError: could not convert string to float: "69.00000'"

This solves it:
```
        index=list(data_price['result'].keys())[0]
        p = data_price['result'][index]['c'][0]
        price.append(p)
        print("Price of ",market[i]," added")
        price[i] = float(price[i])
```

**Comment by smechaab** [comment]
Hi,
Yes, using index as we suppose the data from API is in json form is exact.
I wasn't aware of this at the time it was designed, this is going to be corrected as soon as I got more time :)
Thanks for your support

**Comment by smechaab** [comment]
Bug fixed 👍
